# -*- coding: utf-8 -*-
"""
/***************************************************************************
 geomAttributeDialog
                                 A QGIS plugin
 An attribute table with geometry descriptions
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2018-09-14
        git sha              : $Format:%H$
        copyright            : (C) 2018 by Philip Whitten
        email                : philipwhitten@wollondilly.nsw.gov.au
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

from os import path as osPath
from sys import path as sysPath
from PyQt5 import uic
from PyQt5 import QtWidgets

#   The system path needs to include the directory of the icons
sysPath.append(osPath.dirname(__file__))

FORM_CLASS, _ = uic.loadUiType(osPath.join(
    osPath.dirname(__file__), 'geomAttribute_window_base.ui'), resource_suffix='')

class geomAttributeWindow(QtWidgets.QMainWindow, FORM_CLASS):
    def __init__(self, parent=None):
        """
        Constructor
        """
        super(geomAttributeWindow, self).__init__(parent)
        #   Set up the user interface that is constructed with Qt Designer.
        self.setupUi(self)




